name: Bloom
options:
  bundleIdPrefix: com.bloom
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true
  groupSortPosition: none

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: false
    SWIFT_STRICT_CONCURRENCY: minimal

targets:
  Bloom:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Bloom
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bloom.periodtracker
        INFOPLIST_FILE: Bloom/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        DEVELOPMENT_TEAM: ""
    entitlements:
      path: Bloom/Bloom.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
